// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcgwmkisrytmehosyali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZ3dta2lzcnl0bWVob3N5YWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjM5MjQsImV4cCI6MjA1ODk5OTkyNH0.ztVqH-K1fDup6RgYISQ-SYoUHoMbavgyIRfbXmhkBiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);