# Development profile with H2 database
spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SUPABASE_PROJECT_URL}/.well-known/jwks.json
  # CORS Configuration
  mvc:
    cors:
      allowed-origins: http://localhost:5173,http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Logging
logging:
  level:
    root: INFO
    com.koushik.techInterviewSim: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO

# Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
