spring:
  application:
    name: tech-interview-sim
  # Default to H2 database for development
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8081}
  error:
    include-message: always
    include-binding-errors: always

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Supabase Configuration (if using Supabase auth)
supabase:
  project-url: ${SUPABASE_PROJECT_URL:your-project-url}
  jwt:
    secret: ${SUPABASE_JWT_SECRET:your-jwt-secret}

# Logging
logging:
  level:
    root: INFO
    com.koushik.techInterviewSim: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
