# Production profile with Supabase PostgreSQL
spring:
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://db.xcgwmkisrytmehosyali.supabase.co:5432/postgres?ssl=true&sslmode=require}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD:07pranithpK}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:QAT7noOCY60fsqzU/APKrfA9KJtm9+tCP+UoUI6M6l/5cLcR06mmAzcjEexMHl0cHxOVLVzz1JPvO0S63ugTUQ==}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Supabase Configuration
supabase:
  project-url: ${SUPABASE_PROJECT_URL:https://xcgwmkisrytmehosyali.supabase.co}
  jwt:
    secret: ${SUPABASE_JWT_SECRET:QAT7noOCY60fsqzU/APKrfA9KJtm9+tCP+UoUI6M6l/5cLcR06mmAzcjEexMHl0cHxOVLVzz1JPvO0S63ugTUQ==}

# Logging
logging:
  level:
    root: INFO
    com.koushik.techInterviewSim: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
